# -*- coding: utf-8 -*-
"""Copy_of_Proyek_Analisis_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W6tJYrGMf1IYmsAexcGW04s23hU9gujR

# Proyek Analisis Data: [Input Nama Dataset]
- **Nama:** Afliza Husniyar Anggraini
- **Email:** aflizahusniyar@gmail.com
- **ID Dicoding:** aflizaanggr

## Menentukan Pertanyaan Bisnis

- Pada tanggal berapa terjadi penyewaan paling banyak?
- Saat kapan terjadi penyewaan sepeda tertinggi? (cuaca, libur/tidak)
- Paling lama nyewa berapa jam?

## Import Semua Packages/Library yang Digunakan
"""

import streamlit
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""## Data Wrangling

### Gathering Data
"""

#Input data day
day_df = pd.read_csv("day.csv")
day_df.head()

#Input data hour
hour_df = pd.read_csv("hour.csv")
hour_df.head(30)

"""**Insight:**
- Data day merangkum aktivitas penyewaan sepeda dalam secara harian. Jadi, 1 baris data day merepresentasikan aktivitas penyewaan selama 1 hari.
- Sedangkan untuk data hour, merepresentasikan aktivitas penyewaan selama 1 jam. Jadi, 24 baris data menunujukkan data penyewaan sepeda selama 1 hari.

### Assessing Data

1. Menilai data day_df
"""

#Mencari informasi tipe data day_df
day_df.info()

#Mencari  duplikasi data day_df
print("Jumlah duplikasi: ", day_df.duplicated().sum())

#Deskripsi Statistik day_df
day_df.describe(include="all")

"""2. Menilai data hour_df"""

#Mencari informasi tipe data hour_df
hour_df.info()

#Mencari duplikasi data hour_df
print("Jumlah duplikasi: ", hour_df.duplicated().sum())

#Deskripsi statistik hour_df
hour_df.describe(include="all")

"""**Insight:**
- Tipe data dteday berupa object, seharusnya berupa datetime. Jadi, pada proses cleaning data, akan dilakukan pengubahan tipe data dteday.
- Kedua data tidak memiliki missing value dan duplikat data.

### Cleaning Data
"""

#Mengubah tipe data dteday
datetime_columns = ["dteday"]

for column in datetime_columns:
    day_df[column] = pd.to_datetime(day_df[column])
    hour_df[column] = pd.to_datetime(hour_df[column])

day_df.info()

hour_df.info()

"""**Insight:**
- tipe data dteday sudah berubah menjadi data bertipe datetime.

## Exploratory Data Analysis (EDA)

### Explore ...
"""

#Menghitung jumlah penyewa casual dan registered berdasarkan cuaca
day_df.groupby(by=["weathersit", "season"]).agg({
    "casual": "sum",
    "registered": "sum",
    "cnt" : "sum"
})

#Menghitung jumlah penyewa casual dan registered berdasarkan hari kerja
day_df.groupby(by="workingday").agg({
    "casual": "sum",
    "registered": "sum",
    "cnt" : "sum"
})

#Menghitung jumlah penyewa casual dan registered berdasarkan jam
hour_df.groupby(by="hr").agg({
    "casual": "sum",
    "registered": "sum",
    "cnt" : "sum"
})

#Menghitung jumlah penyewa casual dan registered berdasarkan hari
day_df.groupby('weekday').agg({
    'casual': 'sum',
    'registered': 'sum',
    'cnt': 'sum'
})

"""**Insight:**
- Penyewaan paling banyak terjadi saat cuaca cerah, dan saat musim gugur, sebanyak 799443 dengan penyewa casual berjumlah 167945 dan penyewa registered berjumlah 631498.
- Penyewaan paling banyak terjadi saat hari kerja sebanyak 2292410 dengan penyewa casual sebanyak 303285 dan penyewa registered sebanyak 1989125.
- Penyewaan paling banyak terjadi di jam 17  sebanyak 336860 dengan penyewa casual sebanyak 54220 dan penyewa registered sebanyak 282640.
- Penyewaan paling banyak terjadi di hari 5 sebanyak 487790 dengan penyewa casual sebanyak 78238 dan penyewa registered sebanyak 409552.

## Visualization & Explanatory Analysis

### Pertanyaan 1: Bagaimana faktor cuaca seperti suhu (temp, atemp), kelembaban (hum), dan kecepatan angin (windspeed) mempengaruhi jumlah penyewaan sepeda?
"""

correlation = day_df[["temp", "atemp", "hum", "windspeed", "weathersit","cnt"]].corr()

plt.figure(figsize=(10,6))
sns.heatmap(correlation, annot=True, cmap= "coolwarm", fmt=".2f", square=True)
plt.title("Korelasi antara cuaca dengan Penyewaan Sepeda")
plt.show()

"""**Kesimpulan :**
1. Terdapat korelasi positif antara temperatur dan jumlah penyewa. Hal ini menunjukkan bahwa peningkatan suhu memengaruhi banyaknya jumlah penyewa.
2. Terdapat korelasi negatif antara kelembapan, kecepetan angin, dan cuaca. Hal ini menunjukkan bahwa peningkatan jumlah penyewa berbanding terbalik dengan nilai kelembapan, kecepatan angin, dan cuaca. Namun, hal ini tidak berpengaruh banyak karena nilai korelasinya yang cukup kecil.
"""

#Rata-rata jumlah penyewaan sepeda berdasarkan  suhu
day_df['temp_bins'] = pd.cut(day_df['temp'], bins=[0, 0.2, 0.4, 0.6, 0.8, 1], labels=['Very Low', 'Low', 'Medium', 'High', 'Very High'])
weather_effect = day_df.groupby('temp_bins')['cnt'].mean()
print(weather_effect)

plt.figure(figsize=(8, 6))
sns.barplot(x=weather_effect.index, y=weather_effect.values, palette='Blues_d')

plt.title('Rata-rata Penyewaan Sepeda Berdasarkan Suhu', fontsize=16)
plt.xlabel('Kategori Suhu', fontsize=12)
plt.ylabel('Rata-rata Jumlah Penyewaan (cnt)', fontsize=12)

plt.show()

"""**Kesimpulan:**
- Penyewa cenderung menyewa sepeda pada saat suhunya tinggi atau di cuaca yang cerah, namun bukan di suhu yang tinggi sekali.

### Pertanyaan 2: Bagaimana Tren penyewaan berdasarkan jam tertentu (kelompokkan jam menjadi waktu pagi, siang, sorem malam)?
"""

#Mengelompokkan jam menjadi kategori : pagi, siang, sore, dan malem
def categorize_time(hour):
    if 4 <= hour <= 10:
        return 'Pagi'
    elif 10 < hour <= 14:
        return 'Siang'
    elif 14 < hour <= 18:
        return 'Sore'
    else:
        return 'Malam'

hour_df['time_category'] = hour_df['hr'].apply(categorize_time)
hour_df['time_category'].head(30)

hour_df['time_category'] = pd.Categorical(hour_df['time_category'], categories=['Pagi', 'Siang', 'Sore', 'Malam'], ordered=True)
time_trend = hour_df.groupby('time_category')['cnt'].sum().sort_index()
print(time_trend)

plt.figure(figsize=(8, 5))
sns.barplot(x=time_trend.index, y=time_trend.values, palette='viridis')
plt.title('Jumlah Penyewaan Sepeda Berdasarkan Waktu')
plt.xlabel('Waktu')
plt.ylabel('Jumlah Penyewaan')
plt.show()

"""**Kesimpulan:**
- Tren penyewaan sepeda tertinggi terjadi saat sore hari.

### Pertanyaan 3: Bagaimana pola pengguna Casual vs Registered?
"""

# Menghitung rata-rata penyewaan untuk casual dan registered
user_pattern = day_df[['weekday', 'casual', 'registered']].groupby('weekday').mean().reset_index()
print(user_pattern)

plt.figure(figsize=(12, 6))
sns.lineplot(data=user_pattern, x='weekday', y='casual', marker='o', label='Casual')
sns.lineplot(data=user_pattern, x='weekday', y='registered', marker='o', label='Registered')
plt.title('Rata-rata Penyewaan Sepeda Casual vs Registered per Hari dalam Seminggu')
plt.xlabel('Hari dalam Seminggu')
plt.ylabel('Rata-rata Jumlah Penyewaan')
plt.xticks(ticks=[0, 1, 2, 3, 4, 5, 6], labels=['Minggu', 'Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu'])
plt.legend()
plt.show()

"""**Insight:**
- Penyewa cenderung menyewa sepeda pada saat suhunya tinggi atau di cuaca yang cerah, namun bukan di suhu yang tinggi sekali.
- Tren penyewaan sepeda tertinggi terjadi saat sore hari.
- Penyewa sepeda casual cenderung melakukan sewa saat weekdays dibandingkan saat weekend.
- Sedangkan  penyewa sepeda registered.

## Conclusion

1. Penyewa cenderung menyewa sepeda pada saat suhunya tinggi atau di cuaca yang cerah, namun bukan di suhu yang tinggi sekali.
2. Tren penyewaan sepeda tertinggi terjadi saat sore hari.
3. Penyewa sepeda casual cenderung melakukan sewa saat weekdays dibandingkan saat weekend.Sedangkan  penyewa sepeda registered lebih banyak melakukan sewa saat weekend.
"""
